all:
	g++ -x c++ -std=c++11 main.cpp gl3w.c -I/Users/chirag/work/hacktx-2016/game/sw/include -L/Users/chirag/work/hacktx-2016/game/sw/lib -lglfw -framework Cocoa -framework OpenGL -framework IOKit -opong
