all:
	g++ -g -x c++ -std=c++11 lighting.cpp main.cpp mesh.cpp gl3w.c shader.cpp -I/Users/chirag/work/hacktx-2016/game/sw/include -L/Users/chirag/work/hacktx-2016/game/sw/lib -lglfw -framework Cocoa -framework OpenGL -framework IOKit -opong
